name: simple_lck
description: "쉽고 간단하게 lck 일정을 확인하세요"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  scrollable_positioned_list: ^0.3.8
  http: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lightmode/BNK FEARX.png
    - assets/lightmode/DN Freecs.png
    - assets/lightmode/Dplus KIA.png
    - assets/lightmode/DRX.png
    - assets/lightmode/Gen.G.png
    - assets/lightmode/Hanwha Life Esports.png
    - assets/lightmode/KT Rolster.png
    - assets/lightmode/Nongshim RedForce.png
    - assets/lightmode/OKSavingsBank BRION.png
    - assets/lightmode/T1.png
    - assets/darkmode/BNK FEARX.png
    - assets/darkmode/DN Freecs.png
    - assets/darkmode/Dplus KIA.png
    - assets/darkmode/DRX.png
    - assets/darkmode/Gen.G.png
    - assets/darkmode/Hanwha Life Esports.png
    - assets/darkmode/KT Rolster.png
    - assets/darkmode/Nongshim RedForce.png
    - assets/darkmode/OKSavingsBank BRION.png
    - assets/darkmode/T1.png