// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXm7EACYpjNBhQMEPgc0V8KU72LPlZBc',
    appId: '1:122720023297:android:353e4b5f90b5604578a100',
    messagingSenderId: '122720023297',
    projectId: 'lckalert-45a81',
    storageBucket: 'lckalert-45a81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZbbs4MYiNHRpbT2F8lWhIiDEnXDTbMko',
    appId: '1:122720023297:ios:5a37fb81eeeb70a178a100',
    messagingSenderId: '122720023297',
    projectId: 'lckalert-45a81',
    storageBucket: 'lckalert-45a81.firebasestorage.app',
    iosBundleId: 'com.junsince99.simpleLck',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllvOOmlswMlMsONLS5bYFH9nolpiEwx8',
    appId: '1:122720023297:web:22db83c7964900e778a100',
    messagingSenderId: '122720023297',
    projectId: 'lckalert-45a81',
    authDomain: 'lckalert-45a81.firebaseapp.com',
    storageBucket: 'lckalert-45a81.firebasestorage.app',
    measurementId: 'G-GKB1S27RFT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZbbs4MYiNHRpbT2F8lWhIiDEnXDTbMko',
    appId: '1:122720023297:ios:5a37fb81eeeb70a178a100',
    messagingSenderId: '122720023297',
    projectId: 'lckalert-45a81',
    storageBucket: 'lckalert-45a81.firebasestorage.app',
    iosBundleId: 'com.junsince99.simpleLck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBllvOOmlswMlMsONLS5bYFH9nolpiEwx8',
    appId: '1:122720023297:web:cef0cf7923c1eee778a100',
    messagingSenderId: '122720023297',
    projectId: 'lckalert-45a81',
    authDomain: 'lckalert-45a81.firebaseapp.com',
    storageBucket: 'lckalert-45a81.firebasestorage.app',
    measurementId: 'G-4XPC2XQQCH',
  );

}